# Версия приложения
info.app.version=${version}
management.endpoints.web.exposure.include=info

# Настройки сервера
server.port=8101

# Настройки клиента
client.default.port=8102

# Настройки базы данных
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/dataBaseName
spring.datasource.username=postgresUser
spring.datasource.password=postgresPassword

# Настройки hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true

# Для работы методов PUT, PATCH, DELETE
spring.mvc.hiddenmethod.filter.enabled=true

# Настройки Swagger
# Разрешить отправлять Cookie
springdoc.swagger-ui.with-credentials=true

# Настройки JSON Web Token
app.jwt.secretKey=AVeryVeryLongSecurityKeyMustBeSpecifiedHere
app.jwt.tokenPrefix=Bearer 
app.jwt.token.access.expirationAfterHours=3
app.jwt.token.refresh.expirationAfterDays=2
app.jwt.token.refresh.cookiesLifetimeDays=4
app.jwt.authHeader=Authorization

# Настройки проверки активности пользователя
app.user.status.expirationAfterSeconds = 10

# Настройки файлов передаваемых через endpoint
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Настройки путей хранения файлов
app.scene.directory=Files/Scenes
app.avatar.directory=Files/Avatars