# Настройки сервера
server.port=8101

# Настройки клиента
client.default.port=8102

# Настройки базы данных
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/dataBaseName
spring.datasource.username=postgresUser
spring.datasource.password=postgresPassword

# Настройки hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=true

# Для работы методов PUT, PATCH, DELETE
spring.mvc.hiddenmethod.filter.enabled=true

# Настройки Swagger
# Разрешить отправлять Cookie
springdoc.swagger-ui.with-credentials=true

application.jwt.secretKey=AVeryVeryLongSecurityKeyMustBeSpecifiedHere
application.jwt.tokenPrefix=Bearer 
application.jwt.token.access.expirationAfterHours=3
application.jwt.token.refresh.expirationAfterDays=2
application.jwt.token.refresh.cookiesLifetimeDays=4
application.jwt.authHeader=Authorization

application.user.status.expirationAfterSeconds = 10

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

application.scene.directory=Files/Scenes
application.avatar.directory=Files/Avatars